### ISSUE TITLE
npm run start 以及 npm install 时都报错

### ISSUE THREAD

**Issue by hellenHua** [wjq990112/rax-todo#1]
sh: build-scripts: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! todo-list@ start: `build-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the todo-list@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by wjq990112** [comment]
先安装依赖，安装依赖的时候应该没问题吧？我本地没问题，你看看你的环境。

**Comment by hellenHua** [comment]
> 先安装依赖，安装依赖的时候应该没问题吧？我本地没问题，你看看你的环境。
![image](https://user-images.githubusercontent.com/52913794/82851648-f8d34d00-9f32-11ea-9b13-17597cf256f9.png)
应该是没有websocket-driver的原因，并且下载依赖的时候我的node_modules啥也没有
