### ISSUE TITLE
yarn 可以安装 不知道是为啥

### ISSUE THREAD

**Issue by ruoduan-hub** [wjq990112/rax-todo#3]

**Comment by ruoduan-hub** [comment]
![image](https://user-images.githubusercontent.com/42793079/82993084-a24d3800-a032-11ea-8855-eaac608216f5.png)

**Comment by wjq990112** [comment]
建议看一下 Rax 的官方文档，文档里都写的很清楚，我这里只做了一个 Web 的 Demo，要兼容小程序是有 API 限制的。

**Comment by wjq990112** [comment]
如果有问题的话欢迎提 PR 修复。

**Comment by ruoduan-hub** [comment]
打扰了
